/* Generated by Yosys 0.63 (git sha1 5fd39ff3e, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/003_u_block_3/maro_temp/circuit.v:4.1-26.10" *)
module u_block_3(clk, rst_n, green, red, yellow);
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/003_u_block_3/maro_temp/circuit.v:5.14-5.17" *)
  input clk;
  wire clk;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/003_u_block_3/maro_temp/circuit.v:6.14-6.19" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/003_u_block_3/maro_temp/circuit.v:7.13-7.18" *)
  output green;
  wire green;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/003_u_block_3/maro_temp/circuit.v:8.13-8.16" *)
  output red;
  wire red;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/003_u_block_3/maro_temp/circuit.v:9.13-9.19" *)
  output yellow;
  wire yellow;
  assign yellow = 1'h0;
  assign red = 1'h0;
  assign green = 1'h0;
endmodule
