/* Generated by Yosys 0.63 (git sha1 5fd39ff3e, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:4.1-76.10" *)
module u_block_1(clk, cnt, idle, rst_n, s1_red, s2_yellow, s3_green, p_green, p_red, p_yellow);
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:5.14-5.17" *)
  input clk;
  wire clk;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:6.19-6.22" *)
  input [7:0] cnt;
  wire [7:0] cnt;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:7.14-7.18" *)
  input idle;
  wire idle;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:8.14-8.19" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:9.14-9.20" *)
  input s1_red;
  wire s1_red;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:10.14-10.23" *)
  input s2_yellow;
  wire s2_yellow;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:11.14-11.22" *)
  input s3_green;
  wire s3_green;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:12.14-12.21" *)
  output p_green;
  reg p_green;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:13.14-13.19" *)
  output p_red;
  reg p_red;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:14.14-14.22" *)
  output p_yellow;
  reg p_yellow;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:26.5-74.9" *)
  wire _00_;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:26.5-74.9" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* onehot = 32'd1 *)
  reg [3:0] u_block_1_state;
  assign _03_ = ~(cnt[6] | cnt[7]);
  assign _04_ = ~(cnt[4] | cnt[5]);
  assign _05_ = _03_ & _04_;
  assign _06_ = ~(cnt[2] | cnt[3]);
  assign _07_ = cnt[1] & cnt[0];
  assign _08_ = _06_ & _07_;
  assign _09_ = _05_ & _08_;
  assign _10_ = _09_ ? u_block_1_state[1] : u_block_1_state[2];
  assign _02_ = u_block_1_state[0] | _10_;
  assign _11_ = ~(u_block_1_state[3] | u_block_1_state[0]);
  assign _01_ = _11_ & ~(u_block_1_state[2]);
  assign _00_ = _11_ & ~(u_block_1_state[1]);
  always @(posedge clk, negedge rst_n)
    if (!rst_n) u_block_1_state[0] <= 1'h1;
    else u_block_1_state[0] <= 1'h0;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) u_block_1_state[2] <= 1'h0;
    else u_block_1_state[2] <= _02_;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:26.5-74.9" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) p_green <= 1'h0;
    else p_green <= u_block_1_state[3];
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:26.5-74.9" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) p_red <= 1'h0;
    else p_red <= _00_;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/001_u_block_1/maro_temp/circuit.v:26.5-74.9" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) p_yellow <= 1'h0;
    else p_yellow <= _01_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) u_block_1_state[3] <= 1'h0;
    else if (_09_) u_block_1_state[3] <= u_block_1_state[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) u_block_1_state[1] <= 1'h0;
    else if (_09_) u_block_1_state[1] <= u_block_1_state[3];
endmodule
