/* Generated by Yosys 0.63 (git sha1 5fd39ff3e, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:4.1-36.10" *)
module u_block_2(clk, green, p_green, p_red, p_yellow, pass_request, red, rst_n, yellow, cnt);
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:5.14-5.17" *)
  input clk;
  wire clk;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:6.14-6.19" *)
  input green;
  wire green;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:7.14-7.21" *)
  input p_green;
  wire p_green;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:8.14-8.19" *)
  input p_red;
  wire p_red;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:9.14-9.22" *)
  input p_yellow;
  wire p_yellow;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:10.14-10.26" *)
  input pass_request;
  wire pass_request;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:11.14-11.17" *)
  input red;
  wire red;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:12.14-12.19" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:13.14-13.20" *)
  input yellow;
  wire yellow;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:14.18-14.21" *)
  output [7:0] cnt;
  reg [7:0] cnt;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:23.5-34.26" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  assign _001_ = cnt[1] | cnt[0];
  assign _002_ = cnt[2] | _001_;
  assign _003_ = ~(cnt[3] | _002_);
  assign _004_ = cnt[4] | ~(_003_);
  assign _005_ = ~(cnt[4] | cnt[5]);
  assign _006_ = _003_ & _005_;
  assign _007_ = cnt[6] | ~(_006_);
  assign _008_ = cnt[6] ^ _006_;
  assign _009_ = red | ~(p_red);
  assign _010_ = yellow | ~(p_yellow);
  assign _011_ = ~(_009_ & _010_);
  assign _012_ = ~_011_;
  assign _013_ = green | ~(p_green);
  assign _014_ = cnt[1] & cnt[0];
  assign _015_ = cnt[2] | _014_;
  assign _016_ = ~(cnt[3] & _015_);
  assign _017_ = ~(cnt[6] | cnt[7]);
  assign _018_ = _005_ & _017_;
  assign _019_ = ~(_016_ & _018_);
  assign _020_ = green & pass_request;
  assign _021_ = ~(_019_ & _020_);
  assign _022_ = _013_ & _021_;
  assign _023_ = _012_ & _022_;
  assign _000_[6] = _008_ & _023_;
  assign _024_ = ~(cnt[5] ^ _004_);
  assign _025_ = ~(_012_ & _024_);
  assign _026_ = ~(_013_ & _025_);
  assign _000_[5] = _021_ & _026_;
  assign _027_ = cnt[4] ^ _003_;
  assign _028_ = ~(_012_ & _027_);
  assign _029_ = ~(_013_ & _028_);
  assign _000_[4] = _021_ & _029_;
  assign _030_ = ~(cnt[3] & _002_);
  assign _031_ = ~(_009_ & _030_);
  assign _032_ = _003_ | _031_;
  assign _033_ = ~(_010_ & _032_);
  assign _000_[3] = ~(_022_ & _033_);
  assign _034_ = _010_ & _013_;
  assign _035_ = ~(cnt[2] ^ _001_);
  assign _036_ = ~(_009_ & _035_);
  assign _037_ = ~(_034_ & _036_);
  assign _000_[2] = _021_ & _037_;
  assign _038_ = ~(_001_ & _009_);
  assign _039_ = _014_ | _038_;
  assign _040_ = ~(_034_ & _039_);
  assign _000_[1] = ~(_021_ & _040_);
  assign _041_ = cnt[0] | ~(_009_);
  assign _042_ = ~(_010_ & _041_);
  assign _000_[0] = _022_ & _042_;
  assign _043_ = ~(cnt[7] ^ _007_);
  assign _000_[7] = _023_ & _043_;
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:23.5-34.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cnt[0] <= 1'h0;
    else cnt[0] <= _000_[0];
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:23.5-34.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cnt[1] <= 1'h1;
    else cnt[1] <= _000_[1];
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:23.5-34.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cnt[2] <= 1'h0;
    else cnt[2] <= _000_[2];
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:23.5-34.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cnt[3] <= 1'h1;
    else cnt[3] <= _000_[3];
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:23.5-34.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cnt[4] <= 1'h0;
    else cnt[4] <= _000_[4];
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:23.5-34.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cnt[5] <= 1'h0;
    else cnt[5] <= _000_[5];
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:23.5-34.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cnt[6] <= 1'h0;
    else cnt[6] <= _000_[6];
  (* src = "/home/openclawer/Projects/Partition/workspace/optimization_176e00d2/yosys_opt_record/20260320_043008/002_u_block_2/maro_temp/circuit.v:23.5-34.26" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cnt[7] <= 1'h0;
    else cnt[7] <= _000_[7];
endmodule
